# Generated by Django 4.2.6 on 2023-10-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='external_reference_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
