# Generated by Django 4.2.6 on 2023-10-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0002_facility_external_reference_id_facility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='external_reference_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('external_reference_id', models.IntegerField(unique=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailserver.facility')),
            ],
        ),
    ]
