# Generated by Django 4.2.6 on 2023-11-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0003_alter_facility_external_reference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailserver.facility')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailserver.tour')),
            ],
        ),
    ]
