# Generated by Django 4.2.6 on 2023-11-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0004_monitor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitor',
            new_name='MonitorWindow',
        ),
    ]
