# Generated by Django 4.2.6 on 2023-11-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0005_rename_monitor_monitorwindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorwindow',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='monitorwindow',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
