# Generated by Django 4.2.6 on 2023-11-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0006_alter_monitorwindow_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailserver.facility')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailserver.tour')),
            ],
        ),
    ]
