# Generated by Django 4.2.6 on 2024-01-23 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailserver', '0009_remove_monitorwindow_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='monitorwindow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitorwindow',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monitorwindow',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emailserver.useremail'),
        ),
    ]
